### ISSUE TITLE
[Bug Report][3.3.23] npm default preset scaffolding

### ISSUE THREAD

**Issue by MortenKL** [vuetifyjs/create-vuetify#33] opened 2023-10-25 20:02 UTC
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 11.7.10

### Steps to reproduce
npm create vuetify
choose preset: Default (Vuetify)

### Expected Behavior
installation with default (Vuetify) scaffolding

### Actual Behavior
✖ SyntaxError: Expected double-quoted property name in JSON at position 243

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/)

### Other comments
This problem occurs when choosing the default preset.

**Comment by KaelWD** [comment] 2023-11-09 04:27
Duplicate of #30

**Closed by KaelWD** 2023-11-09 04:27 UTC
